### ISSUE TITLE
Is the Personal Access Token needed?

### ISSUE THREAD

**Issue by kowale** [zulip/zulip-archive#43]
Hello! I was wondering if there was a way to not share the user's GitHub Personal Access Token with other people when using zulip-archive inside an organization. That is, to make a zulip-archive instance for an organization, one needs to create a PAT for a member with relevant permissions and store it in a secret accessible from within the organization i.e. an organization repository secret or an organization-wide secret. In both cases, other members of the organization can access the generated PAT, which (with the `repo` and `workflow` permissions) could be used to make changes to all of the owner's repositories. More details on the scopes are [here](https://docs.github.com/en/developers/apps/scopes-for-oauth-apps).

I remembered that I used [actions-gh-pages](https://github.com/peaceiris/actions-gh-pages) for some other GH page with static files (generated with Zola) and it only needed the generic `secrets.GITHUB_TOKEN` as described [here](https://docs.github.com/en/actions/configuring-and-managing-workflows/authenticating-with-the-github_token).
```yaml
on:
  push:
    branches:
      - source # Default branch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup
      uses: actions/checkout@v2
    - name: Build
      run: |
            VERSION="v0.11.0"
            curl -L https://github.com/getzola/zola/releases/download/$VERSION/zola-$VERSION-x86_64-unknown-linux-gnu.tar.gz > zola.tar.gz
            tar -xzf zola.tar.gz
            ./zola build
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        publish_branch: master # Deploying branch (not default)
```

The `entrypoint.sh` in zulip-archive seems to do all the work that could be delegated to `actions-gh-pages` and specifically uses the PAT as the token. Could this be substituted with a token either specific to the organization (i.e. the OAuth App) or the `secrets.GITHUB_TOKEN` as described above? One potential issue with using the latter is some additional steps on first run, described [here](https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-first-deployment-with-github_token).

Is there a reason for which the PAT was preferred? Apologies if I missed something obvious here and thanks for reading!
